spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/gateway_database
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082

logging:
  level:
    org.hibernate.orm.connections.pooling: off